### ISSUE TITLE
merge-var.fasta 

### ISSUE THREAD

**Issue by summerghw** [bzhanglab/customprodbj#1]
Hello, 
    I found that the costomized database merge-var.fasta had two kind of headers , one was 

> VAR|NM_001287816|357 NM_001287816 c.C1433T p.S478L protein-altering  (position 478 changed from S to L)

and the other was 

> NM_001288995

Is that means that the sequnces startswith VAR was mutant and the others was same in Refseq so that i just need to deal with the sequnces startswith VAR.
Thank you!

**Comment by wenbostar** [comment]
Yes.

**Comment by summerghw** [comment]
@wenbostar hello，I only find two papers  relative to this software, 《customProDB: an R package to generate customized protein databases from RNA-Seq data for proteomics search》 and 《Protein identification using customized protein sequence databases derived from RNA-Seq data》
    I have some questions: 
       1.does customProDB(R package) have the same algorithm with customprodbj.
       2.what exactly the algorithm is, or is there any paper tlak about it.   does it was same with quilts (https://github.com/ekawaler/pyQUILTS)

**Comment by wenbostar** [comment]
The new tool customprodbj is different from customProDB (R package) and pyQUILTS. It mainly builds customized databases based on ANNOAR annotation result.

**Comment by summerghw** [comment]
thank you for reply, does that means customprodbj is only suit for vcf files, do not contain Expression filting based on RPKM and Junction analysis functions.  so that , if i have both RNAseq and WES/WGS data, i need to builds cutomized databases respectively.

**Comment by wenbostar** [comment]
Customprodbj was designed for variants from WES/WGS/RNA-Seq data. It doesn't support Junction nor filtering based on RPKM.
