### ISSUE TITLE
customprodbj.jar: cannot find mRNA sequence for NM_001349904 in the fasta file!

### ISSUE THREAD

**Issue by wanghao1991217** [bzhanglab/customprodbj#2]
I have use the CTAT-mutation pepline to call variants from RNAseq datasets, then used the table_annovar.pl to do varient annotation agaist the hg38 build database. But there's something wrong when ruuning the customprodbj.jar: WARNING: cannot find mRNA sequence for NM_016196 in the fasta file! And the corresponding merge-var.fasta file were blank. 
Here's my code:

### Variant annotation using ANNOVAR:

```bash
for i in $(ls /media/rchenubuntu/5618DC8B18DC6B8D/CTAT_mutation.variants.HC_hard_cutoffs_applied.vcf | sed s/.vcf//); do perl /home/rchenubuntu/software/annovar.latest/annovar/table_annovar.pl /media/rchenubuntu/5618DC8B18DC6B8D/CTAT_mutation.variants.HC_hard_cutoffs_applied.vcf/$i.vcf /media/rchenubuntu/5618DC8B18DC6B8D/annover_database/humandb -buildver hg38 -out /media/rchenubuntu/5618DC8B18DC6B8D/annover_out/$i -protocol refGene -operation g -nastring . -vcfinput --thread 46 --maxgenethread 46 -polish ; done
```

### Build customized protein database using Customprodbj:

```java
java -jar /home/rchenubuntu/software/customprodbj-1.0.0.jar -i /media/rchenubuntu/5618DC8B18DC6B8D/annover_out/multianno/A_382607.hg38_multianno.txt -d annovar_database/humandb/hg38_refGeneMrna.fa -r annovar_database/humandb/hg38_refGene.txt -t -o /media/rchenubuntu/5618DC8B18DC6B8D/customprodbj1.0.0_output/
```

![image](https://user-images.githubusercontent.com/35870021/94328951-73979c00-ffe9-11ea-941a-fbb34eeda661.png)

I have check the NM_001270372 in the fa file. It exist.

![image](https://user-images.githubusercontent.com/35870021/94328984-c5402680-ffe9-11ea-99e2-475cb3dc2151.png)

**Comment by wenbostar** [comment]
Could you try this version: [1.2](https://github.com/wenbostar/Customprodbj/releases/download/v1.2.0/customprodbj-1.2.0.jar)?

**Comment by wanghao1991217** [comment]
@wenbostar 
Sorry, because of my negligence, I didn't give the absolute path of ref fasta files, which led to the error, and has nothing to do with the software version. Thank you for help.

**Comment by wenbostar** [comment]
No problem.
